### PR TITLE
Board id to UUID

### PR DESCRIPTION
**Pull request by ryguigas0**
Updated Schemas, Migrations and tests related to the change

### CODE REVIEW

**Comment by zorn** [comment]
```diff
diff --git a/lib/retro_taxi/boards.ex b/lib/retro_taxi/boards.ex
index 670c31f..10eccb3 100644
--- a/lib/retro_taxi/boards.ex
+++ b/lib/retro_taxi/boards.ex
@@ -57,7 +57,7 @@ defmodule RetroTaxi.Boards do
 
     iex> board = RetroTaxi.Boards.get_board!(1, [:columns])
   """
-  @spec get_board!(integer(), keyword() | nil) :: Board.t()
+  @spec get_board!(Board.id(), keyword() | nil) :: Board.t()
   def get_board!(id, preloads \\ []) do
     Board
     |> Repo.get!(id)
@@ -74,7 +74,7 @@ defmodule RetroTaxi.Boards do
 
     iex> {:ok, board} = RetroTaxi.Boards.fetch_board(1, [:columns])
   """
-  @spec fetch_board(integer(), keyword() | nil) :: {:ok, Board.t()} | :not_found
+  @spec fetch_board(Board.id(), keyword() | nil) :: {:ok, Board.t()} | :not_found
   def fetch_board(id, preloads \\ []) do
     case Repo.get(Board, id) do
       nil -> :not_found

```

**Comment by zorn** [comment]
Was hoping VS Code would have posted those as the easy inline "approve suggestions" but none the less. 

This looks great. Thanks so much for contributing. In the future I think it would be important to apply the database schema changes as a migration but since this has not yet been deployed I think editing the old migration files is fine. I do it myself. The recommended changes are to help keep dialyizer happy.

**Comment by ryguigas0** [comment]
Sorry I forgot to set the right types. Dialyzer is a Erlang debug tool right? I don't know how to use it, do you know any tutorials about this?

**Comment by zorn** [comment]
No worries. Here is the run down:

> Dialyzer is a static analysis tool that identifies software discrepancies, such as definite type errors, code that has become dead or unreachable because of programming error, and unnecessary tests, in single Erlang modules or entire (sets of) applications.

http://erlang.org/doc/man/dialyzer.html

Dialyxir is:

> Mix tasks to simplify use of Dialyzer in Elixir projects.

https://hexdocs.pm/dialyxir/readme.html

This let's you run `mix dialyzer` on the project to verify the typespecs defined.

A good introduction for typespecs can be found:

https://elixirschool.com/en/lessons/advanced/typespec

https://elixir-lang.org/getting-started/typespecs-and-behaviours.html#types-and-specs

**Pull request merged**
